version: "3.8"

services:
  sd-webui:
    build: .
    working_dir: /stable-diffusion-webui
    ports:
      - "7860:7860"
    volumes:
      - ./models:/stable-diffusion-webui/models
      - ./outputs:/stable-diffusion-webui/outputs
