version: "3.8"

services:
  sd-webui:
    build: .
    working_dir: /stable-diffusion-webui
    ports:
      - "7860:7860"
    volumes:
      - ./models/Stable-diffusion:/stable-diffusion-webui/models/Stable-diffusion
      - ./outputs:/stable-diffusion-webui/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
